# This is a basic workflow to help you get started with Actions

name: CLI-user-java

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths: 
      - 'apis/user-java/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

     # Runs a set of commands using the runners shell
      - name: Logs into Azure
        run: |
          echo "Logging into Azure"
          az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
      - name: Builds image
        run: |
          echo "Building API-user-java image..."
          echo ${GITHUB_RUN_NUMBER}
          #echo "Changing directory to $GITOHTEAMDIRPATH/apis/user-java..."
          cd apis/user-java
          pwd
          az acr build --image "devopsoh/api-user-java:${GITHUB_RUN_NUMBER}" --registry ${{ secrets.REGISTRY }} --file Dockerfile .
          
      - name: Pushes image to ACR and updates the staging slot webapp to the new image
        run: |
          az webapp config show --name openhack62d3tcj1userjava --resource-group openhack62d3tcj1rg --slot staging 
          az webapp config container set --name openhack62d3tcj1userjava --resource-group openhack62d3tcj1rg --slot staging --docker-custom-image-name='DOCKER|openhack62d3tcj1acr.azurecr.io/devopsoh/api-user-java:'${GITHUB_RUN_NUMBER} 
                
  
